# Generated by Django 4.2.2 on 2023-06-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_airport_status_schedule_status_alter_flight_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="available_seats",
            field=models.IntegerField(default=60),
        ),
    ]
