# Generated by Django 4.2.2 on 2023-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_alter_schedule_available_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule", name="available_seats", field=models.IntegerField(),
        ),
    ]
